from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('validate/', views.validate, name='validate'),
    path('logout_user/', views.logout_user, name='logout_user'),

    path('worker-home/', views.worker_home, name='worker_home'),
    path('worker-profile/', views.worker_profile, name='worker_profile'),
    path('worker-profile/update-worker-account/', views.update_worker_account, name='update_worker_account'),
    path('worker-schedule/', views.worker_schedule, name='worker_schedule'),
    path('worker-schedule/get-worker-schedules/', views.get_worker_schedules, name='get_worker_schedules'),
    path('worker-attendance/', views.worker_attendance, name='worker_attendance'),
    path('worker-attendance/search-attendance/', views.search_attendance, name='search_attendance'),
    path('worker-payroll/', views.worker_payroll, name='worker_payroll'),


    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('attendance-report/<int:project_id>/', views.attendance_report, name='attendance_report'),
    path('attendance-report/all/', views.attendance_report_all, name='attendance_report_all'),
    path('payroll-report/<int:project_id>/', views.payroll_report, name='payroll_report'),
    path('payroll-report/all/', views.payroll_report_all, name='payroll_report_all'),
    path('overall-report/<int:project_id>/', views.get_overall_project_report, name='get_overall_project_report'),
    path('project_report/<int:project_id>/', views.project_report_view, name='project_report'),
    path('admin_accounts/', views.admin_accounts, name='admin_accounts'),
    path('admin_accounts/add_accountPage/', views.add_accountPage, name='add_accountPage'),
    path('admin_accounts/add_accountPage/check-username/', views.check_username, name='check_username'),
    path('admin_accounts/add_accountPage/add_account/', views.add_account, name='add_account'),
    path('admin_accounts/accountDetails_page/<int:id>/', views.accountDetails_page, name='accountDetails_page'),
    path('admin_accounts/search_accounts/', views.search_accounts, name='search_accounts'),
    path('admin_accounts/filter_accounts/', views.filter_accounts, name='filter_accounts'),
    path('admin_accounts/deactivate-account/<int:account_id>/', views.deactivate_account, name='deactivate_account'),
    path('admin_accounts/account-history/', views.account_history, name='account_history'),
    path('admin_accounts/account-history/accountDetails_page/<int:id>/', views.accountDetails_page, name='accountDetails_page'),
    path('admin_accounts/activate-account/<int:account_id>/', views.activate_account, name='activate_account'),
    path('admin-projects/', views.admin_projects, name='admin_projects'),
    path('admin-projects/project-details/<int:id>', views.admin_project_details, name='admin_project_details'),
    path('admin-projects/project-details/update-project/<int:id>', views.update_project, name='update_project'),
    path('admin-projects/search-projects/', views.search_projects, name='search_projects'),
    path('admin-projects/create-project-page', views.create_Projectpage, name='create_Projectpage'),
    path('admin-projects/create-project-page/register-project', views.registerProject, name='registerProject'),


    path('foreman_home/', views.foreman_home, name='foreman_home'),
    path('foreman_attendance/', views.foreman_attendance, name='foreman_attendance'),
    path('foreman_attendance/get-attendance-data/<int:worker_id>/', views.get_attendance_data, name='get_attendance_data'),
    path('foreman_attendance/filter-attendance/', views.filter_attendance, name='filter_attendance'),
    path('foreman_attendance/QRcamera', views.foreman_QRcamera, name='QRcamera'),
    path('foreman_attendance/QRcamera/get-worker-info/<int:account_id>/', views.get_worker_info, name='get_worker_info'),
    path('foreman_attendance/QRcamera/record-attendance/<int:account_id>/', views.record_attendance, name='record_attendance'),
    path('foreman_progress/', views.foreman_progress, name='foreman_progress'),
    path('foreman_progress/search-tasks/', views.search_tasks, name='search_tasks'),
    path('foreman_progress/filter-task/', views.filter_task, name='filter_task'),
    path('foreman_progress/get-task-details/<int:task_id>/', views.get_task_details, name='get_task_details'),
    path('foreman_progress/update-progress/<int:task_id>/', views.update_progress, name='update_progress'),
    path('foreman_progress/update-progress-after-completed/<int:task_id>/', views.update_progress_after_completed, name='update_progress_after_completed'),
    path('foreman_account/', views.foreman_account, name='foreman_account'),
    path('foreman_account/update_foreman_account/', views.update_foreman_account, name='update_foreman_account'),
    path('foreman_project/', views.foreman_project, name='foreman_project'),
    path('foreman_project/get-project-details/<int:id>/', views.foreman_get_project_details, name='foreman_get_project_details'),
    path('foreman_project/add-resource/<int:id>/', views.foreman_add_resource, name='foreman_add_resource'),
    path('foreman_project/foreman-update-resource/', views.foreman_update_resource, name='foreman_update_resource'),
    path('foreman_project/foreman-delete-resource/', views.foreman_delete_resource, name='foreman_delete_resource'),
    path('foreman_project/foreman-search-projects/', views.foreman_search_projects, name='foreman_search_projects'),
    path("foreman_project/mark-finished/<int:project_id>/", views.mark_project_finished, name="mark_project_finished"),
    path('foreman_project/foreman_task_schedule/', views.foreman_task_schedule, name='foreman_task_schedule'),
    path('foreman_project/add-taskSchedule/', views.add_taskSchedule, name='add_taskSchedule'),
    path('foreman_project/add-taskSchedule/get_project_percentage/<int:project_id>/', views.get_project_percentage, name='get_project_percentage'),
    path('foreman_project/foreman_task_schedule/update_taskSchedule/', views.update_taskSchedule, name='update_taskSchedule'),

    
    path('project-manager-home/', views.project_manager_home, name='project_manager_home'),
    path('project-manager-account/', views.PM_account, name='PM_account'),
    path('project-manager-account/update-PM-account', views.update_PM_account, name='update_PM_account'),
    path('project-manager-team/', views.PM_manageTeam, name='PM_manageTeam'),
    path('project-manager-team/project/<int:project_id>/worker/<int:worker_id>/info/', views.fetch_worker_details, name='fetch_worker_details'),
    #path('project-manager-team/fetch-payroll-details/<int:worker_id>/<int:project_id>/', views.fetch_payroll_details, name='fetch_payroll_details'),
    #path('project-manager-team/fetch-payroll-details/update-payroll/<int:worker_id>/<int:project_id>/', views.update_payroll, name='update_payroll'),
    path('project-manager-team/add-bonus/<int:project_id>/<int:worker_id>/', views.add_bonus, name="add_bonus"),
    path('project-manager-team/add-deduction/<int:project_id>/<int:worker_id>/', views.add_deduction, name="add_deduction"),
    path('project-manager-team/search-projects/', views.search_projects, name='search_projects'),
    path('project-manager-projects/', views.PM_manageProject, name='PM_manageProject'),
    path('project-manager-projects/edit-project/<int:id>', views.PM_edit_project, name='PM_edit_project'),
    path('project-manager-projects/update-project/<int:id>', views.PM_update_project, name='PM_update_project'),
    path('finalize_project/<int:id>/', views.PM_finalize_project, name='PM_finalize_project'),
    path('project-manager-projects/search-project/', views.PM_search_projects, name='PM_search_projects'),
    path('project-manager-resources/', views.PM_manageResources, name='PM_manageResources'),
    path('project-manager-resources/add-resource/<int:project_id>/', views.PM_add_resource, name='PM_add_resource'),
    path('project-manager-resources/update-resource/<int:resource_id>/', views.PM_update_resource, name='PM_update_resource'),
    path('project-manager-resources/delete-resource/<int:resource_id>/', views.PM_delete_resource, name='PM_delete_resource'),
]