# Generated by Django 5.1.1 on 2024-09-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('PM', 'Project Manager'), ('FM', 'Foreman'), ('worker', 'Worker')], max_length=50)),
            ],
        ),
    ]
