# Generated by Django 5.1.1 on 2024-09-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
