# Generated by Django 5.1.1 on 2024-09-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0002_rename_accounts_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
