# Generated by Django 5.1.1 on 2024-10-09 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0003_alter_account_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personnel_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CPMMS.account')),
            ],
        ),
    ]
