# Generated by Django 5.1.1 on 2024-10-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0005_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='CPMMS/QR_codes'),
        ),
    ]
