# Generated by Django 5.1.1 on 2024-10-11 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0006_worker_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='profile.webp', upload_to='CPMMS/Profile_imgs'),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
