# Generated by Django 5.1.1 on 2024-10-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0007_account_date_created_account_image_account_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='time_created',
        ),
    ]
