# Generated by Django 5.1.1 on 2024-10-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0008_remove_account_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
