# Generated by Django 5.1.1 on 2024-10-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0009_alter_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='qr_code_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
