# Generated by Django 5.1.1 on 2024-10-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0010_worker_qr_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
