# Generated by Django 5.1.1 on 2024-10-30 01:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0011_personnel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_status', models.CharField(max_length=50)),
                ('worker_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CPMMS.worker')),
            ],
        ),
    ]
