# Generated by Django 5.1.1 on 2024-10-30 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0013_alter_attendance_time_in_alter_attendance_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='recorded_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
