# Generated by Django 5.1.1 on 2024-11-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0014_alter_attendance_recorded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('contract', models.ImageField(upload_to='CPMMS/Contracts')),
                ('project_percent', models.IntegerField()),
            ],
        ),
    ]
