# Generated by Django 5.1.1 on 2024-11-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0015_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_percent',
            field=models.IntegerField(default=0),
        ),
    ]
