# Generated by Django 5.1.1 on 2024-11-02 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0016_alter_project_project_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
