# Generated by Django 5.1.1 on 2024-11-02 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0017_project_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
