# Generated by Django 5.1.1 on 2024-11-02 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0018_alter_project_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='personnel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CPMMS.personnel'),
        ),
    ]
