# Generated by Django 5.1.1 on 2024-11-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0019_project_personnel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='personnel_id',
        ),
        migrations.AddField(
            model_name='project',
            name='foreman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_foreman', to='CPMMS.personnel'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_manager', to='CPMMS.personnel'),
        ),
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to='CPMMS.worker'),
        ),
    ]
