# Generated by Django 5.1.1 on 2024-11-06 11:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0020_remove_project_personnel_id_project_foreman_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_manager',
            new_name='project_manager_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='foreman',
        ),
        migrations.RemoveField(
            model_name='project',
            name='workers',
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('TaskSchedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_name', models.CharField(max_length=50)),
                ('date_start', models.DateField()),
                ('deadline', models.DateField()),
                ('percent_from_project', models.IntegerField()),
                ('task_status', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('foreman_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPMMS.personnel')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CPMMS.project')),
                ('workers', models.ManyToManyField(blank=True, related_name='assigned_tasks', to='CPMMS.worker')),
            ],
        ),
    ]
