# Generated by Django 5.1.1 on 2024-11-07 01:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0021_rename_project_manager_project_project_manager_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_progress', models.IntegerField()),
                ('remarks', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='CPMMS/Progress')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='progress_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CPMMS.progress'),
        ),
    ]
