# Generated by Django 5.1.1 on 2024-11-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0022_progress_taskschedule_progress_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='remarks',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='description',
            field=models.TextField(default='None', max_length=100),
        ),
    ]
