# Generated by Django 5.1.1 on 2024-11-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0023_alter_progress_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='worker_progress',
            field=models.IntegerField(default=0),
        ),
    ]
