# Generated by Django 5.1.1 on 2024-11-07 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0024_alter_progress_worker_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='CPMMS.project'),
        ),
    ]
