# Generated by Django 5.1.1 on 2024-11-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0025_alter_taskschedule_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='CPMMS.account'),
        ),
    ]
