# Generated by Django 5.1.1 on 2024-11-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0026_alter_personnel_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='image',
        ),
    ]
