# Generated by Django 5.1.1 on 2024-11-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0027_remove_progress_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='task_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('halfway', 'Halfway Completed'), ('nearly_completed', 'Nearly Completed'), ('completed', 'Completed')], default='not_started', max_length=50),
        ),
    ]
