# Generated by Django 5.1.1 on 2024-11-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0028_alter_taskschedule_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='None', max_length=100, null=True),
        ),
    ]
