# Generated by Django 5.1.1 on 2024-11-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0029_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='No Description', max_length=100, null=True),
        ),
    ]
