# Generated by Django 5.1.1 on 2024-11-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0030_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timeframe',
            field=models.ImageField(null=True, upload_to='CPMMS/Timeframes'),
        ),
    ]
