# Generated by Django 5.1.1 on 2024-11-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0031_project_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(default='Not Started', max_length=50, null=True),
        ),
    ]
