# Generated by Django 5.1.1 on 2024-11-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0032_project_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='timeIn_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='timeOut_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
