# Generated by Django 5.1.1 on 2024-11-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0033_remove_attendance_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10, null=True),
        ),
    ]
