# Generated by Django 5.1.1 on 2024-11-23 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0034_attendance_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
