# Generated by Django 5.1.1 on 2024-11-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0035_alter_attendance_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_foreman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_foreman', to='CPMMS.personnel'),
        ),
    ]
