# Generated by Django 5.1.1 on 2024-11-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0036_project_assigned_foreman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('supplies_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('cost', models.IntegerField(default=0)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='CPMMS.project')),
            ],
        ),
    ]
