# Generated by Django 5.1.1 on 2024-11-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0037_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='cost_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
