# Generated by Django 5.1.1 on 2024-11-25 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0038_resources_cost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
