# Generated by Django 5.1.1 on 2024-11-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0039_resources_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='created_at',
        ),
    ]
