# Generated by Django 5.1.1 on 2024-11-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0040_remove_resources_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
    ]
