# Generated by Django 5.1.1 on 2024-11-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0041_rename_resources_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='supplies_id',
            new_name='resource_id',
        ),
    ]
