# Generated by Django 5.1.1 on 2024-11-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0042_rename_supplies_id_resource_resource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='added_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
