# Generated by Django 5.1.1 on 2024-12-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0043_resource_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=12, null=True),
        ),
    ]
