# Generated by Django 5.1.1 on 2024-12-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0044_worker_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='estimated_payment',
            field=models.IntegerField(null=True),
        ),
    ]
