# Generated by Django 5.1.1 on 2024-12-06 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0045_taskschedule_estimated_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('bonus', models.CharField(max_length=50)),
                ('deductions', models.CharField(max_length=50)),
                ('total_amount', models.IntegerField()),
                ('worker_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_payroll', to='CPMMS.worker')),
            ],
        ),
    ]
