# Generated by Django 5.1.1 on 2024-12-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0046_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='CPMMS.project'),
        ),
    ]
