# Generated by Django 5.1.1 on 2024-12-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0047_attendance_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_payroll', to='CPMMS.project'),
        ),
    ]
