# Generated by Django 5.1.1 on 2024-12-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0048_payroll_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='timeOut_status',
        ),
    ]
