# Generated by Django 5.1.1 on 2024-12-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0049_remove_attendance_timeout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='bonus',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deductions',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
