# Generated by Django 5.1.1 on 2024-12-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0050_alter_payroll_bonus_alter_payroll_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=12, null=True),
        ),
    ]
