# Generated by Django 5.1.1 on 2024-12-13 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0051_personnel_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('material', 'Material'), ('supply', 'Supply'), ('equipment', 'Equipment')], max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('material', 'Material'), ('supply', 'Supply'), ('equipment', 'Equipment')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CPMMS.resourcesubtype'),
        ),
    ]
