# Generated by Django 5.1.1 on 2024-12-14 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0052_resourcesubtype_alter_resource_type_resource_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskschedule',
            name='estimated_payment',
        ),
    ]
