# Generated by Django 5.1.1 on 2024-12-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0053_remove_taskschedule_estimated_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_deactivated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='worker_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='CPMMS.worker'),
        ),
    ]
