# Generated by Django 5.1.1 on 2024-12-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0054_account_date_deactivated_alter_attendance_worker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
