# Generated by Django 5.1.1 on 2025-02-09 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0055_alter_account_date_deactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_personal_info', to='CPMMS.account'),
        ),
    ]
