# Generated by Django 5.1.1 on 2025-02-09 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0056_alter_worker_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='deductions',
        ),
        migrations.CreateModel(
            name='Payroll_Bonus',
            fields=[
                ('bonus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bonus_name', models.CharField(max_length=50)),
                ('bonus_amount', models.IntegerField(default=0)),
                ('payroll_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_bonus', to='CPMMS.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll_Deduction',
            fields=[
                ('deduction_id', models.AutoField(primary_key=True, serialize=False)),
                ('deduction_name', models.CharField(max_length=50)),
                ('deduction_amount', models.IntegerField(default=0)),
                ('payroll_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_deductions', to='CPMMS.worker')),
            ],
        ),
    ]
