# Generated by Django 5.1.1 on 2025-02-10 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0057_remove_payroll_bonus_remove_payroll_deductions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_bonus',
            name='payroll_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_bonus', to='CPMMS.payroll'),
        ),
        migrations.AlterField(
            model_name='payroll_deduction',
            name='payroll_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_deductions', to='CPMMS.payroll'),
        ),
    ]
