# Generated by Django 5.1.1 on 2025-03-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0058_alter_payroll_bonus_payroll_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
