# Generated by Django 5.1.1 on 2025-03-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0059_project_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finalization_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
