# Generated by Django 5.1.1 on 2025-03-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPMMS', '0060_project_finalization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finalization_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Finalizing', 'Finalizing'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
